### PR TITLE
feat(seed): update policies to standard

### PR DESCRIPTION
**Pull request by jjeroch**
## Description

Updating seeding data to latest association standards

- Added new enum useCaseIds
- Enhanced policies
- updated existing policies
- enhanced policy to useCase assignment

## Why

Updating seeding data to latest association standards

## Issue

n/a

## Checklist

Please delete options that are not relevant.

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/policy-hub/blob/main/docs/technical-documentation/dev-process/How%20to%20contribute.md)

### CODE REVIEW

**Comment by jjeroch** [comment]
@Phil91  I have added enums and changed 3 existing policies - do we need to do anything else to apply such changes?

**Comment by jjeroch** [comment]
Unit test update missing

**Comment by Phil91** [comment]
> @Phil91 I have added enums and changed 3 existing policies - do we need to do anything else to apply such changes?

we need to add a migration for that as well. I can take care of this

**Comment by evegufy** [comment]
> > @Phil91 I have added enums and changed 3 existing policies - do we need to do anything else to apply such changes?
> 
> we need to add a migration for that as well. I can take care of this

could you please directly name it rc2?

**Review by evegufy — APPROVED** [review]

**Pull request merged**
